const UserActionTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  RESET_ERRORS: "RESET_ERRORS",
  GET_USER_LIST_START: "GET_USER_LIST_START",
  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_FAILURE: "GET_USER_LIST_FAILURE",
  ADD_UPDATE_USER_START: "ADD_UPDATE_USER_START",
  ADD_UPDATE_USER_SUCCESS: "ADD_UPDATE_USER_SUCCESS",
  ADD_UPDATE_USER_FAILURE: "ADD_UPDATE_USER_FAILURE",
  GET_USER_DETAIL_START: "GET_USER_DETAIL_START",
  GET_USER_DETAIL_SUCCESS: "GET_USER_DETAIL_SUCCESS",
  GET_USER_DETAIL_FAILURE: "GET_USER_DETAIL_FAILURE",
};

export default UserActionTypes;
